Migration flow
nighthawk-apps/nighthawk-ios-wallet pull request #7
Opened 2023-08-14 12:37 UTC by tw0po1nt

Implement the migration flow from an old wallet to a new one

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Does the code abide by the [Coding Guidelines](../blob/main/docs/CODING_GUIDELINES.md)?
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/main/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage before and after your changes and when possible, leave it in a better place. [Learn More...](../blob/main/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/main/README.md), [LICENSE.md](../blob/main/LICENSE.md), and [Architecture.md](../blob/main/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2023-08-14 12:39 UTC, tw0po1nt commented on modules/Sources/Dependencies/WalletStorage/WalletStorage.swift
> +        guard let wallet = try decode(json: data, as: StoredWallet.self) else {
Reverting it to how it was before, as this change broke some things.

2023-08-14 12:42 UTC, tw0po1nt reviewed
Finished self-review

2023-08-15 18:54 UTC, pacu commented
I followed the steps and got this error:

```
action:
  RootReducer.Action.initialization(.migrateLegacyWallet)
  RootReducer.State(
-   _alert: nil,
+   _alert: AlertState(
+     title: "Migration failed",
+     message: "An error occurred and we were unable to migrate your wallet automatically. Tap continue to import your wallet manually."
+   ),
    appInitializationState: .needsMigration,
    debugState: RootReducer.DebugState(rescanDialog: nil),
    destinationState: RootReducer.DestinationState(…),
    exportLogsState: ExportLogsReducer.State(…),
    nhHomeState: NHHomeReducer.State(…),
    homeState: HomeReducer.State(…),
    migrateState: MigrateReducer.State(),
    onboardingState: OnboardingFlowReducer.State(…),
    phraseValidationState: RecoveryPhraseValidationFlowReducer.State(…),
    phraseDisplayState: RecoveryPhraseDisplayReducer.State(…),
    sandboxState: SandboxReducer.State(…),
    storedWallet: StoredWallet(…),
    walletConfig: WalletConfig(…),
    welcomeState: WelcomeReducer.State()
  )
  ```

2023-08-15 22:11 UTC, pacu requested changes
Unfortunately my manual test failed. :(

Plus code review comments need resolution.

2023-08-15 22:11 UTC, pacu commented on modules/Sources/Features/Root/RootInitialization.swift
> +                    walletStorage.nukeLegacyWallet()
shouldn't we attempt to delete the legacy storage after we are sure that they were successfully migrated?

2023-08-15 22:11 UTC, pacu commented on secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "version" : "0.10.0"
possibly unwanted version downgrade

2023-08-15 22:11 UTC, pacu commented on secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "version" : "0.3.0"
possibly unwanted version downgrade

2023-08-15 22:11 UTC, pacu commented on secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "version" : "0.5.1"
possibly unwanted version downgrade

2023-08-15 22:11 UTC, pacu commented on secant.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "version" : "0.7.2"
possibly unwanted version downgrade

2023-08-15 22:14 UTC, pacu commented
More testing feedback.

Apparently is not that I got an error, it's that There's no feedback from the app. 

If the user taps once on the migrate button, the app starts to scan but there's no feedback about it.

If the user force-closes the app and restarts it the app will got to the homescreen.

2023-08-16 14:33 UTC, tw0po1nt commented on modules/Sources/Features/Root/RootInitialization.swift
> +                    walletStorage.nukeLegacyWallet()
Yeah probably!

2023-08-18 14:08 UTC, pacu approved these changes

2023-08-18 14:10 UTC, merged